export const coins = {
  "BTC": { "id": 1, "tags": [] },
  "STX": { "id": 2, "tags": ["Bitcoin Layer 2"] },
  "RIF": { "id": 3, "tags": ["Bitcoin Layer 2"] },
  "BADGER": { "id": 4, "tags": ["Bitcoin DeFi"] },
  "REN": { "id": 5, "tags": ["Bitcoin DeFi"] },
  "ETH": { "id": 6, "tags": [] },
  "MATIC": { "id": 7, "tags": ["ZK", "Layer 2"] },
  "OP": { "id": 8, "tags": ["Layer 2"] },
  "LRC": { "id": 9, "tags": ["ZK", "Layer 2"] },
  "DUSK": { "id": 10, "tags": ["ZK"] },
  "BNB": { "id": 11, "tags": [] },
  "HOOK": { "id": 12, "tags": ["Binance LaunchPad"] },
  "WRX": { "id": 13, "tags": ["Binance LaunchPad"] },
  "VGX": { "id": 14, "tags": ["Binance LaunchPad"] },
  "TKO": { "id": 15, "tags": ["Binance LaunchPad"] },
  "SOL": { "id": 16, "tags": ["New Chains"] },
  "ATOM": { "id": 17, "tags": ["New Chains"] },
  "FTM": { "id": 18, "tags": ["New Chains"] },
  "APT": { "id": 19, "tags": ["New Chains"] },
  "DOT": { "id": 20, "tags": ["New Chains"] },
  "DOGE": { "id": 21, "tags": ["Meme", "Elon"] },
  "SHIB": { "id": 22, "tags": ["Meme", "Elon"] },
  "MASK": { "id": 23, "tags": ["Meme", "Elon"] },
  "FIL": { "id": 24, "tags": ["Storage"] },
  "AR": { "id": 25, "tags": ["Storage"] },
  "SC": { "id": 26, "tags": ["Storage"] },
  "STORJ": { "id": 27, "tags": ["Storage"] },
  "BLZ": { "id": 28, "tags": ["Storage"] },
  "AGIX": { "id": 29, "tags": ["AI"] },
  "FET": { "id": 30, "tags": ["AI"] },
  "CFX": { "id": 31, "tags": ["HongKong"] },
  "ACH": { "id": 32, "tags": ["HongKong"] },
  "KEY": { "id": 33, "tags": ["HongKong"] },
  "MDT": { "id": 34, "tags": ["HongKong"] },
  "NEO": { "id": 35, "tags": ["HongKong"] },
  "LDO": { "id": 36, "tags": ["LSD"] },
  "RPL": { "id": 37, "tags": ["LSD"] },
  "FXS": { "id": 38, "tags": ["LSD"] },
  "FIS": { "id": 39, "tags": ["LSD"] },
  "YFI": { "id": 40, "tags": ["LSD"] },
  "CRV": { "id": 41, "tags": ["Stablecoin"] },
  "MKR": { "id": 42, "tags": ["Stablecoin"] },
  "TRU": { "id": 43, "tags": ["Stablecoin"] },
  "LQTY": { "id": 44, "tags": ["Stablecoin"] },
  "SPELL": { "id": 45, "tags": ["Stablecoin"] },
  "UNI": { "id": 46, "tags": ["Swap"] },
  "CAKE": { "id": 47, "tags": ["Swap"] },
  "GMX": { "id": 48, "tags": ["Perp"] },
  "DYDX": { "id": 49, "tags": ["Perp"] },
  "PERP": { "id": 50, "tags": ["Perp"] },
  "TWT": { "id": 51, "tags": ["Wallet"] },
  "SFP": { "id": 52, "tags": ["Wallet"] },
  "SAND": { "id": 53, "tags": ["Metaverse"] },
  "MANA": { "id": 54, "tags": ["Metaverse"] },
  "RNDR": { "id": 55, "tags": ["Metaverse"] },
  "HIGH": { "id": 56, "tags": ["Metaverse"] },
  "MAGIC": { "id": 57, "tags": ["Metaverse"] },
  "ENS": { "id": 58, "tags": ["Web3"] },
  "GTC": { "id": 59, "tags": ["Web3"] },
  "GAL": { "id": 60, "tags": ["Web3"] },
  "ANT": { "id": 61, "tags": ["Web3"] },
  "LIT": { "id": 62, "tags": ["Web3"] },
  "LTC": { "id": 63, "tags": ["Halving"] },
  "DASH": { "id": 64, "tags": ["Halving"] },
  "BCH": { "id": 65, "tags": ["Halving"] }
}
